test:
  tags: [test]
  script:
    - cp -r build/ /var/www/test-app/$CI_COMMIT_SHA

#stages:
#  - build
#  - test
#  - deploy
#
#install_dependencies:
#  image: node:14.15.0-stretch
#  stage: build
#  script:
#    - yarn install
#    - yarn build
#  artifacts:
#    paths:
#      - node_modules
#      - build
#  cache:
#    key:
#      files:
#        - yarn.lock
#    paths:
#      - node_modules

#run_tests:
#  image: node:14.15.0-stretch
#  stage: test
#  script: CI=true yarn test

#deploy:
#  stage: deploy
#  script:
#    - ls -lha
#    - find build
      





