stages:
  - build
  - test
  - deploy

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
      - static
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

run_tests:
  image: node:14.15.0-stretch
  stage: test
  script: CI=true yarn test

deploy:
  stage: deploy
  script: ls -lha statis

