stages:
  - build
  - test
  - deploy
  - revert

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
      - build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

test:
  stage: deploy
  script:
    - cp -r build /www/test-app/$CI_COMMIT_SHA
    - cp -Pv /www/html /www/test-app/$CI_COMMIT_SHA/prev-version
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA /www/html

revert:
  stage: revert
  when: manual
  script:
    - cp -Pv --remove-destination /www/test-app/$CI_COMMIT_SHA/prev-version /www/html


