stages:
  - build
  - test
  - deploy
  - revert

variables:
  docker_html_path: "/www"
  deploy_subfolder: html

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

#run_tests:
#  image: node:14.15.0-stretch
#  stage: test
#  script: CI=true yarn test

deploy_staging:
  stage: deploy
  extends: activate_prod
  variables:
    deploy_subfolder: staging/$CI_COMMIT_BRANCH
  when: always

deploy:
  stage: deploy
  script:
    - cp -r build $docker_html_path/test-app/$CI_COMMIT_SHA
    - cp -Pv $docker_html_path/$deploy_subfolder $docker_html_path/test-app/$CI_COMMIT_SHA/prev-version

activate_prod:
  stage: deploy
  script: 
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA $docker_html_path/$deploy_subfolder
  when: manual

revert:
  stage: revert
  when: manual
  script: 
    - cp -Pv --remove-destination  $docker_html_path/test-app/$CI_COMMIT_SHA/prev-version $docker_html_path/html
