stages:
  - build
  - test
  - deploy

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - export
    - ls /dsfdsf
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
      - build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

#run_tests:
#  image: node:14.15.0-stretch
#  stage: test
#  script: CI=true yarn test

#deploy:
#  stage: deploy
# script:
#    - ls -lha
#    - find build

test:
  stage: deploy
  script:
    - cp -r build /www/test-app/$CI_COMMIT_SHA
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA /www/html
    - ls /sdfdsf




