stages:
  - build
  - test
  - deploy
  - revert

variables:
  docker_html_path: "/www"

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
      - build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

run_tests:
  image: node:14.15.0-stretch
  stage: test
  script: CI=true yarn test

deploy:
  stage: deploy
  script:
    - ls -lha
    - find build

test:
  stage: deploy
  script:
    - cp -r build $docker_html_path/test-app/$CI_COMMIT_SHA
    - cp -Pv $docker_html_path/html $docker_html_path/test-app/$CI_COMMIT_SHA/prev-version
    - ln -fsnv /var/www/test-app/$CI_COMMIT_SHA $docker_html_path/html

revert:
  stage: revert
  when: manual
  script: 
    - cp -Pv --remove-destination  $docker_html_path/test-app/$CI_COMMIT_SHA/prev-version $docker_html_path/html
