stages:
  - build
  - test
  - deploy

install_dependencies:
  image: node:14.15.0-stretch
  stage: build
  tags: [test]
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules
      - build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

#run_tests:
#  image: node:14.15.0-stretch
#  tags: [test]
#  stage: test
#  script: CI=true yarn test

#deploy:
#  stage: deploy
#   tags: [test]
# script:
#    - ls -lha
#    - find build

test:
  stage: deploy
  tags: [test]
  script:
    - cp -r build/ /var/www/test-app/$CI_COMMIT_SHA
 


